use onepiece;

-- Popolamento completo tabella products
INSERT INTO products (id, name, description, price, image_url, category, personaggio, active) VALUES
(1, 'Poster 1.5m', 'Descrizione di Poster 1.5m', 19.90, 'Poster_15m.jpg', 'Poster e Stampe', 'Luffy', TRUE),
(2, 'Maglia Bandiera', 'Descrizione di Maglia Bandiera', 19.90, 'Maglia_Bandiera.jpg', 'Magliette', 'Luffy', TRUE),
(3, 'Maglia Legend', 'Descrizione di Maglia Legend', 19.90, 'Maglia_Legend.jpg', 'Magliette', 'Luffy', TRUE),
(4, 'Maglia Occhiata', 'Descrizione di Maglia Occhiata', 19.90, 'Maglia_Occhiata.jpg', 'Magliette', 'Luffy', TRUE),
(5, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Luffy', TRUE),
(6, 'Quadro Gear4', 'Descrizione di Quadro Gear4', 19.90, 'Quadro_Gear4.jpg', 'Poster e Stampe', 'Luffy', TRUE),
(7, 'Quadro Wano', 'Descrizione di Quadro Wano', 19.90, 'Quadro_Wano.jpg', 'Poster e Stampe', 'Luffy', TRUE),
(8, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Luffy', TRUE),
(9, 'Maglia Snakeman', 'Descrizione di Maglia Snakeman', 19.90, 'Maglia_Snakeman.jpg', 'Magliette', 'Luffy', TRUE),
(10, 'Cosplay Wano', 'Descrizione di Cosplay Wano', 19.90, 'Cosplay_Wano.jpg', 'Cosplay', 'Luffy', TRUE),
(11, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Luffy', TRUE),
(12, 'Figure Gear4', 'Descrizione di Figure Gear4', 19.90, 'Figure_Gear4.jpg', 'Action Figures', 'Luffy', TRUE),
(13, 'Figure ASL', 'Descrizione di Figure ASL', 19.90, 'Figure_ASL.jpg', 'Action Figures', 'Luffy', TRUE),
(14, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Luffy', TRUE),
(15, 'Figure w/Law', 'Descrizione di Figure w/Law', 19.90, 'Figure_w_Law.jpg', 'Action Figures', 'Luffy', TRUE),
(16, 'Figure w/Ace', 'Descrizione di Figure w/Ace', 19.90, 'Figure_w_Ace.jpg', 'Action Figures', 'Luffy', TRUE),
(17, 'Quadro Wano', 'Descrizione di Quadro Wano', 19.90, 'Quadro_Wano.jpg', 'Poster e Stampe', 'Zoro', TRUE),
(18, 'Poster 120m', 'Descrizione di Poster 120m', 19.90, 'Poster_120m.jpg', 'Poster e Stampe', 'Zoro', TRUE),
(19, 'Poster 320m', 'Descrizione di Poster 320m', 19.90, 'Poster_320m.jpg', 'Poster e Stampe', 'Zoro', TRUE),
(20, 'Maglia Albero', 'Descrizione di Maglia Albero', 19.90, 'Maglia_Albero.jpg', 'Magliette', 'Zoro', TRUE),
(21, 'Maglia Luna', 'Descrizione di Maglia Luna', 19.90, 'Maglia_Luna.jpg', 'Magliette', 'Zoro', TRUE),
(22, 'Cosplay Wano', 'Descrizione di Cosplay Wano', 19.90, 'Cosplay_Wano.jpg', 'Cosplay', 'Zoro', TRUE),
(23, 'Maglia Santoryu', 'Descrizione di Maglia Santoryu', 19.90, 'Maglia_Santoryu.jpg', 'Magliette', 'Zoro', TRUE),
(24, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Zoro', TRUE),
(25, 'Quadro Asura', 'Descrizione di Quadro Asura', 19.90, 'Quadro_Asura.jpg', 'Poster e Stampe', 'Zoro', TRUE),
(26, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Zoro', TRUE),
(27, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Zoro', TRUE),
(28, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Zoro', TRUE),
(29, 'Figure BountyHunter', 'Descrizione di Figure BountyHunter', 19.90, 'Figure_BountyHunter.jpg', 'Action Figures', 'Zoro', TRUE),
(30, 'Figure New World', 'Descrizione di Figure New World', 19.90, 'Figure_New_World.jpg', 'Action Figures', 'Sanji', TRUE),
(31, 'Poster 330m', 'Descrizione di Poster 330m', 19.90, 'Poster_330m.jpg', 'Poster e Stampe', 'Sanji', TRUE),
(32, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Sanji', TRUE),
(33, 'Cosplay Wano', 'Descrizione di Cosplay Wano', 19.90, 'Cosplay_Wano.jpg', 'Cosplay', 'Sanji', TRUE),
(34, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Sanji', TRUE),
(35, 'Figure SobaMask', 'Descrizione di Figure SobaMask', 19.90, 'Figure_SobaMask.jpg', 'Action Figures', 'Sanji', TRUE),
(36, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Sanji', TRUE),
(37, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Jinbei', TRUE),
(38, 'Poster 400m', 'Descrizione di Poster 400m', 19.90, 'Poster_400m.jpg', 'Poster e Stampe', 'Jinbei', TRUE),
(39, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Jinbei', TRUE),
(40, 'Poster 130m', 'Descrizione di Poster 130m', 19.90, 'Poster_130m.jpg', 'Poster e Stampe', 'Robin', TRUE),
(41, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Robin', TRUE),
(42, 'Cosplay Wano', 'Descrizione di Cosplay Wano', 19.90, 'Cosplay_Wano.jpg', 'Cosplay', 'Robin', TRUE),
(43, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Robin', TRUE),
(44, 'Figure Queen', 'Descrizione di Figure Queen', 19.90, 'Figure_Queen.jpg', 'Action Figures', 'Robin', TRUE),
(45, 'Figure New World', 'Descrizione di Figure New World', 19.90, 'Figure_New_World.jpg', 'Action Figures', 'Robin', TRUE),
(46, 'Poster 83m', 'Descrizione di Poster 83m', 19.90, 'Poster_83m.jpg', 'Poster e Stampe', 'Brook', TRUE),
(47, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Brook', TRUE),
(48, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Brook', TRUE),
(49, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Brook', TRUE),
(50, 'Figure Soul', 'Descrizione di Figure Soul', 19.90, 'Figure_Soul.jpg', 'Action Figures', 'Brook', TRUE),
(51, 'Figure New World', 'Descrizione di Figure New World', 19.90, 'Figure_New_World.jpg', 'Action Figures', 'Brook', TRUE),
(52, 'Poster 94m', 'Descrizione di Poster 94m', 19.90, 'Poster_94m.jpg', 'Poster e Stampe', 'Franky', TRUE),
(53, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Franky', TRUE),
(54, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Franky', TRUE),
(55, 'Figure Shogun', 'Descrizione di Figure Shogun', 19.90, 'Figure_Shogun.jpg', 'Action Figures', 'Franky', TRUE),
(56, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Franky', TRUE),
(57, 'Cosplay Wano', 'Descrizione di Cosplay Wano', 19.90, 'Cosplay_Wano.jpg', 'Cosplay', 'Nami', TRUE),
(58, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Nami', TRUE),
(59, 'Poster 66m', 'Descrizione di Poster 66m', 19.90, 'Poster_66m.jpg', 'Poster e Stampe', 'Nami', TRUE),
(60, 'Figure Chibi', 'Descrizione di Figure Chibi', 19.90, 'Figure_Chibi.jpg', 'Action Figures', 'Nami', TRUE),
(61, 'Figure Queen', 'Descrizione di Figure Queen', 19.90, 'Figure_Queen.jpg', 'Action Figures', 'Nami', TRUE),
(62, 'Figure Pre', 'Descrizione di Figure Pre', 19.90, 'Figure_Pre.jpg', 'Action Figures', 'Nami', TRUE),
(63, 'Poster 100', 'Descrizione di Poster 100', 19.90, 'Poster_100.jpg', 'Poster e Stampe', 'Chopper', TRUE),
(64, 'Maglia', 'Descrizione di Maglia', 19.90, 'Maglia.jpg', 'Magliette', 'Chopper', TRUE),
(65, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Chopper', TRUE),
(66, 'Pelouche', 'Descrizione di Pelouche', 19.90, 'Pelouche.jpg', 'Pelouches', 'Chopper', TRUE),
(67, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Chopper', TRUE),
(68, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Chopper', TRUE),
(69, 'Figure Horn Point', 'Descrizione di Figure Horn Point', 19.90, 'Figure_Horn_Point.jpg', 'Action Figures', 'Chopper', TRUE),
(70, 'Poster 200m', 'Descrizione di Poster 200m', 19.90, 'Poster_200m.jpg', 'Poster e Stampe', 'Usopp', TRUE),
(71, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Usopp', TRUE),
(72, 'Figure New World', 'Descrizione di Figure New World', 19.90, 'Figure_New_World.jpg', 'Action Figures', 'Usopp', TRUE),
(73, 'Figure Sogeking', 'Descrizione di Figure Sogeking', 19.90, 'Figure_Sogeking.jpg', 'Action Figures', 'Usopp', TRUE),
(74, 'Figure w/Luffy', 'Descrizione di Figure w/Luffy', 19.90, 'Figure_w_Luffy.jpg', 'Action Figures', 'Law', TRUE),
(75, 'Maglia', 'Descrizione di Maglia', 19.90, 'Maglia.jpg', 'Magliette', 'Law', TRUE),
(76, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Law', TRUE),
(77, 'Quadro', 'Descrizione di Quadro', 19.90, 'Quadro.jpg', 'Poster e Stampe', 'Law', TRUE),
(78, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Law', TRUE),
(79, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Law', TRUE),
(80, 'Figure NeW World', 'Descrizione di Figure NeW World', 19.90, 'Figure_NeW_World.jpg', 'Action Figures', 'Law', TRUE),
(81, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Kidd', TRUE),
(82, 'Figure ASL', 'Descrizione di Figure ASL', 19.90, 'Figure_ASL.jpg', 'Action Figures', 'Ace', TRUE),
(83, 'Maglia', 'Descrizione di Maglia', 19.90, 'Maglia.jpg', 'Magliette', 'Ace', TRUE),
(84, 'Poster 550m', 'Descrizione di Poster 550m', 19.90, 'Poster_550m.jpg', 'Poster e Stampe', 'Ace', TRUE),
(85, 'Figure w/Luffy', 'Descrizione di Figure w/Luffy', 19.90, 'Figure_w_Luffy.jpg', 'Action Figures', 'Ace', TRUE),
(86, 'Maglia Barbabianca', 'Descrizione di Maglia Barbabianca', 19.90, 'Maglia_Barbabianca.jpg', 'Magliette', 'Ace', TRUE),
(87, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Ace', TRUE),
(88, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Ace', TRUE),
(89, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Ace', TRUE),
(90, 'Figure ASL', 'Descrizione di Figure ASL', 19.90, 'Figure_ASL.jpg', 'Action Figures', 'Sabo', TRUE),
(91, 'Pelouche', 'Descrizione di Pelouche', 19.90, 'Pelouche.jpg', 'Pelouches', 'Sabo', TRUE),
(92, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Sabo', TRUE),
(93, 'Figure Flame Emperor', 'Descrizione di Figure Flame Emperor', 19.90, 'Figure_Flame_Emperor.jpg', 'Action Figures', 'Sabo', TRUE),
(94, 'Poster 4M', 'Descrizione di Poster 4M', 19.90, 'Poster_4M.jpg', 'Poster e Stampe', 'Shanks', TRUE),
(95, 'Cosplay', 'Descrizione di Cosplay', 19.90, 'Cosplay.jpg', 'Cosplay', 'Shanks', TRUE),
(96, 'Quadro Colorful', 'Descrizione di Quadro Colorful', 19.90, 'Quadro_Colorful.jpg', 'Poster e Stampe', 'Shanks', TRUE),
(97, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Shanks', TRUE),
(98, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Shanks', TRUE),
(99, 'Figure Chibi', 'Descrizione di Figure Chibi', 19.90, 'Figure_Chibi.jpg', 'Action Figures', 'Shanks', TRUE),
(100, 'Poster 4M', 'Descrizione di Poster 4M', 19.90, 'Poster_4M.jpg', 'Poster e Stampe', 'Kaido', TRUE),
(101, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Kaido', TRUE),
(102, 'Poster 5M', 'Descrizione di Poster 5M', 19.90, 'Poster_5M.jpg', 'Poster e Stampe', 'Barbabianca', TRUE),
(103, 'Maglia', 'Descrizione di Maglia', 19.90, 'Maglia.jpg', 'Magliette', 'Barbabianca', TRUE),
(104, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Barbabianca', TRUE),
(105, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Barbabianca', TRUE),
(106, 'Poster 2M', 'Descrizione di Poster 2M', 19.90, 'Poster_2M.jpg', 'Poster e Stampe', 'Barbanera', TRUE),
(107, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Barbanera', TRUE),
(108, 'Figure King', 'Descrizione di Figure King', 19.90, 'Figure_King.jpg', 'Action Figures', 'Barbanera', TRUE),
(109, 'Poster 5M', 'Descrizione di Poster 5M', 19.90, 'Poster_5M.jpg', 'Poster e Stampe', 'Roger', TRUE),
(110, 'Quadro', 'Descrizione di Quadro', 19.90, 'Quadro.jpg', 'Poster e Stampe', 'Roger', TRUE),
(111, 'Figure', 'Descrizione di Figure', 19.90, 'Figure.jpg', 'Action Figures', 'Roger', TRUE),
(112, 'Going Merry', 'Descrizione di Going Merry', 19.90, 'Going_Merry.jpg', 'Gadget Vari', NULL, TRUE),
(113, 'Queen Mama Chanter', 'Descrizione di Queen Mama Chanter', 19.90, 'Queen_Mama_Chanter.jpg', 'Gadget Vari', NULL, TRUE),
(114, 'Baratie', 'Descrizione di Baratie', 19.90, 'Baratie.jpg', 'Gadget Vari', NULL, TRUE),
(115, 'Arca Maxim', 'Descrizione di Arca Maxim', 19.90, 'Arca_Maxim.jpg', 'Gadget Vari', NULL, TRUE),
(116, 'Thousand Sunny', 'Descrizione di Thousand Sunny', 19.90, 'Thousand_Sunny.jpg', 'Gadget Vari', NULL, TRUE),
(117, 'Portachiavi Cappello', 'Descrizione di Portachiavi Cappello', 19.90, 'Portachiavi_Cappello.jpg', 'Gadget Vari', NULL, TRUE),
(118, 'Portachiavi Luffy', 'Descrizione di Portachiavi Luffy', 19.90, 'Portachiavi_Luffy.jpg', 'Gadget Vari', NULL, TRUE),
(119, 'Portachiavi Luffy Wano', 'Descrizione di Portachiavi Luffy Wano', 19.90, 'Portachiavi_Luffy_Wano.jpg', 'Gadget Vari', NULL, TRUE),
(120, 'Portachiavi Monster Trio', 'Descrizione di Portachiavi Monster Trio', 19.90, 'Portachiavi_Monster_Trio.jpg', 'Gadget Vari', NULL, TRUE),
(121, 'Portachiavi Jolly Roger Zoro', 'Descrizione di Portachiavi Jolly Roger Zoro', 19.90, 'Portachiavi_Jolly_Roger_Zoro.jpg', 'Gadget Vari', NULL, TRUE),
(122, 'Portachiavi Zoro', 'Descrizione di Portachiavi Zoro', 19.90, 'Portachiavi_Zoro.jpg', 'Gadget Vari', NULL, TRUE),
(123, 'Portachiavi Jolly Roger Sanji', 'Descrizione di Portachiavi Jolly Roger Sanji', 19.90, 'Portachiavi_Jolly_Roger_Sanji.jpg', 'Gadget Vari', NULL, TRUE),
(124, 'Portachiavi Sanji', 'Descrizione di Portachiavi Sanji', 19.90, 'Portachiavi_Sanji.jpg', 'Gadget Vari', NULL, TRUE),
(125, 'Portachiavi Robin', 'Descrizione di Portachiavi Robin', 19.90, 'Portachiavi_Robin.jpg', 'Gadget Vari', NULL, TRUE),
(126, 'Portachiavi Brook', 'Descrizione di Portachiavi Brook', 19.90, 'Portachiavi_Brook.jpg', 'Gadget Vari', NULL, TRUE),
(127, 'Portachiavi Nami', 'Descrizione di Portachiavi Nami', 19.90, 'Portachiavi_Nami.jpg', 'Gadget Vari', NULL, TRUE),
(128, 'Portachiavi Chopper', 'Descrizione di Portachiavi Chopper', 19.90, 'Portachiavi_Chopper.jpg', 'Gadget Vari', NULL, TRUE),
(129, 'Portachiavi Usopp', 'Descrizione di Portachiavi Usopp', 19.90, 'Portachiavi_Usopp.jpg', 'Gadget Vari', NULL, TRUE),
(130, 'Portachiavi Law', 'Descrizione di Portachiavi Law', 19.90, 'Portachiavi_Law.jpg', 'Gadget Vari', NULL, TRUE),
(131, 'Portachiavi Sabo', 'Descrizione di Portachiavi Sabo', 19.90, 'Portachiavi_Sabo.jpg', 'Gadget Vari', NULL, TRUE),
(132, 'Portachiavi Ace', 'Descrizione di Portachiavi Ace', 19.90, 'Portachiavi_Ace.jpg', 'Gadget Vari', NULL, TRUE),
(133, 'Portachiavi Cappello Ace', 'Descrizione di Portachiavi Cappello Ace', 19.90, 'Portachiavi_Cappello_Ace.jpg', 'Gadget Vari', NULL, TRUE),
(134, 'Portachiavi Jolly Roger Barbabianca', 'Descrizione di Portachiavi Jolly Roger Barbabianca', 19.90, 'Portachiavi_Jolly_Roger_Barbabianca.jpg', 'Gadget Vari', NULL, TRUE),
(135, 'Portafoglio Jolly Roger', 'Descrizione di Portafoglio Jolly Roger', 19.90, 'Portafoglio_Jolly_Roger.jpg', 'Portafogli', NULL, TRUE),
(136, 'Portafoglio Chopper', 'Descrizione di Portafoglio Chopper', 19.90, 'Portafoglio_Chopper.jpg', 'Portafogli', NULL, TRUE),
(137, 'Portafoglio Jolly Roger Law', 'Descrizione di Portafoglio Jolly Roger Law', 19.90, 'Portafoglio_Jolly_Roger_Law.jpg', 'Portafogli', NULL, TRUE),
(138, 'Portafoglio Ace', 'Descrizione di Portafoglio Ace', 19.90, 'Portafoglio_Ace.jpg', 'Portafogli', NULL, TRUE),
(139, 'Bracciale Logo', 'Descrizione di Bracciale Logo', 19.90, 'Bracciale_Logo.jpg', 'Bracciali', NULL, TRUE),
(140, 'Bracciale Jolly Roger', 'Descrizione di Bracciale Jolly Roger', 19.90, 'Bracciale_Jolly_Roger.jpg', 'Bracciali', NULL, TRUE),
(141, 'Bracciale Ace', 'Descrizione di Bracciale Ace', 19.90, 'Bracciale_Ace.jpg', 'Bracciali', NULL, TRUE),
(142, 'Cappello Luffy', 'Descrizione di Cappello Luffy', 19.90, 'Cappello_Luffy.jpg', 'Cappelli', NULL, TRUE),
(143, 'Cappello Chopper', 'Descrizione di Cappello Chopper', 19.90, 'Cappello_Chopper.jpg', 'Cappelli', NULL, TRUE),
(144, 'Cappello Ace', 'Descrizione di Cappello Ace', 19.90, 'Cappello_Ace.jpg', 'Cappelli', NULL, TRUE),
(145, 'Cappello Barbabianca', 'Descrizione di Cappello Barbabianca', 19.90, 'Cappello_Barbabianca.jpg', 'Cappelli', NULL, TRUE),
(146, 'Poster Arca Maxim', 'Descrizione di Poster Arca Maxim', 19.90, 'Poster_Arca_Maxim.jpg', 'Poster e Stampe', NULL, TRUE),
(147, 'Poster Going Merry', 'Descrizione di Poster Going Merry', 19.90, 'Poster_Going_Merry.jpg', 'Poster e Stampe', NULL, TRUE),
(148, 'Poster Thousand Sunny', 'Descrizione di Poster Thousand Sunny', 19.90, 'Poster_Thousand_Sunny.jpg', 'Poster e Stampe', NULL, TRUE),
(149, 'Poster Baratie', 'Descrizione di Poster Baratie', 19.90, 'Poster_Baratie.jpg', 'Poster e Stampe', NULL, TRUE),
(150, 'Poster Queen Mama Chanter', 'Descrizione di Poster Queen Mama Chanter', 19.90, 'Poster_Queen_Mama_Chanter.jpg', 'Poster e Stampe', NULL, TRUE),
(151, 'Maglia Thousand Sunny', 'Descrizione di Maglia Thousand Sunny', 19.90, 'Maglia_Thousand_Sunny.jpg', 'Magliette', NULL, TRUE),
(152, 'Poster Cappello di Paglia', 'Descrizione di Poster Cappello di Paglia', 19.90, 'Poster_Cappello_di_Paglia.jpg', 'Poster e Stampe', NULL, TRUE),
(153, 'Modellino Going Merry', 'Descrizione di Modellino Going Merry', 19.90, 'Modellino_Going_Merry.jpg', 'Modellini', NULL, TRUE),
(154, 'Modellino Thousand Sunny', 'Descrizione di Modellino Thousand Sunny', 19.90, 'Modellino_Thousand_Sunny.jpg', 'Modellini', NULL, TRUE),
(155, 'Modellino Baratie', 'Descrizione di Modellino Baratie', 19.90, 'Modellino_Baratie.jpg', 'Modellini', NULL, TRUE),
(156, 'Modellino Queen Mama Chanter', 'Descrizione di Modellino Queen Mama Chanter', 19.90, 'Modellino_Queen_Mama_Chanter.jpg', 'Modellini', NULL, TRUE),
(157, 'Modellino Arca Maxim', 'Descrizione di Modellino Arca Maxim', 19.90, 'Modellino_Arca_Maxim.jpg', 'Modellini', NULL, TRUE),
(158, 'Poster Wanted Generico', 'Descrizione di Poster Wanted Generico', 19.90, 'Poster_Wanted_Generico.jpg', 'Poster e Stampe', NULL, TRUE);